name: Deploy package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  testing-env:
    if: contains(github.event.head_commit.message, '[major]') || contains(github.event.head_commit.message, '[minor]') || contains(github.event.head_commit.message, '[patch]')
    runs-on: windows-latest
    timeout-minutes: 3

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: .\typescript
        run: npm ci

      - name: Run tests
        working-directory: .\typescript
        run: npm test


  deploying-package:
    if: success()
    needs: [testing-env]
    runs-on: windows-latest
    timeout-minutes: 3
    permissions: 
      contents: write

    strategy:
      fail-fast: false
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        working-directory: .\typescript
        run: npm ci

      - name: Increment version and publish package
        working-directory: .\typescript
        run: |
          $commit_message=(git log --format=%B -n 1 $env:GITHUB_SHA)
          $type = ""
          if ($commit_message -match "\[major\]") {
            $type = "major"
          } elseif ($commit_message -match "\[minor\]") {
            $type = "minor"
          } else {
            $type = "patch"
          }
          
          npm version $type
          git config --global user.email "github_action@github.com"
          git config --global user.name "github_robot"
          git commit --all -m "[Automated commit] - $type release generated"
      
      - name: Publish package
        working-directory: .\typescript
        run: 
          npm publish

      - name: Push commited changes
        working-directory: .\typescript
        run: 
          git push  