name: Deploy package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  testing-env:
    if: contains(github.event.head_commit.message, '[major]') || contains(github.event.head_commit.message, '[minor]') || contains(github.event.head_commit.message, '[patch]')
    runs-on: windows-latest
    timeout-minutes: 3

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  deploying-package:
    if: success()
    needs: [testing-env]
    runs-on: windows-latest
    timeout-minutes: 3
    permissions: 
      contents: write

    strategy:
      fail-fast: false
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
     
      - name: Set up Git
        run: | 
          git config user.email "github_action@github.com"
          git config user.name "github robot"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Increment package version
        run: |
          $commit_message=(git log --format=%B -n 1 $env:GITHUB_SHA)
          $type = ""
          if ($commit_message -match "\[major\]") {
            $type = "major"
          } elseif ($commit_message -match "\[minor\]") {
            $type = "minor"
          } else {
            $type = "patch"
          }
          
          npm version $type
          git commit --allow-empty --all -m "[Automated commit] - $type release generated"
      
      - name: Format code
        run: |
          npm run format
          git commit --allow-empty --all -m "[Automated commit] - formatted Code"

      - name: Publish package
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run dist
          cd dist
          npm publish

      - name: Push commited changes
        env: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: 
          git push  